### ISSUE TITLE
Recuperar mais informações do usuário (nome)

### ISSUE THREAD

**Issue by orivaldosantana** [Natalnet/dataviewer-beta#3]
A rota "users/profile" atualmente retorna apenas o e-mail. É importante retornar também o nome.

**Comment by orivaldosantana** [comment]
Já existe uma rota, mas não está retornado os dados (nome, e-mail, id) do banco de dados

**Comment by luissssmartins** [comment]
As informações estão sendo recuperadas, foi criado recentemente uma maneira de retornar o nome se cadastrado, porém, somente quando a página inicial é atualizada uma segunda vez
